---
- name: Provision MySQL Database Environment
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    mysql_container_name: "mysql_db_automation"
    mysql_root_password: "Secret5555"
    mysql_database: "subscribers_db"
    mysql_user: "dbuser"
    mysql_password: "Secret5555"
    mysql_port: 3306
    flyway_version: "10.8.1"
    
  tasks:
    - name: Pull MySQL Docker image
      community.docker.docker_image:
        name: mysql:8.0
        source: pull
        
    - name: Start MySQL container
      community.docker.docker_container:
        name: "{{ mysql_container_name }}"
        image: mysql:8.0
        state: started
        restart_policy: unless-stopped
        ports:
          - "{{ mysql_port }}:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 5
          
    - name: Wait for MySQL to be ready
      wait_for:
        host: localhost
        port: "{{ mysql_port }}"
        delay: 10
        timeout: 60
        
    - name: Wait additional time for MySQL initialization
      pause:
        seconds: 15
        
    - name: Verify database exists
      community.mysql.mysql_query:
        login_host: localhost
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_db: "{{ mysql_database }}"
        query: "SELECT 1"
      register: db_check
      retries: 5
      delay: 5
      until: db_check is succeeded
      
    - name: Create Flyway Docker network
      community.docker.docker_network:
        name: flyway_network
        
    - name: Connect MySQL container to network
      community.docker.docker_network:
        name: flyway_network
        connected:
          - "{{ mysql_container_name }}"
        appends: yes
        
    - name: Run initial Flyway migrations
      community.docker.docker_container:
        name: flyway_migration_initial
        image: "flyway/flyway:{{ flyway_version }}"
        state: started
        detach: false
        cleanup: yes
        networks:
          - name: flyway_network
        volumes:
          - "{{ playbook_dir }}/../flyway/migrations_initial:/flyway/sql"
        command: >
          -url=jdbc:mysql://{{ mysql_container_name }}:3306/{{ mysql_database }}
          -user={{ mysql_user }}
          -password={{ mysql_password }}
          -connectRetries=5
          migrate
          
    - name: Display success message
      debug:
        msg: 
          - "MySQL environment provisioned successfully!"
          - "Database: {{ mysql_database }}"
          - "User: {{ mysql_user }}"
          - "Port: {{ mysql_port }}"
          - "Initial migrations completed"